version: "3.8"

services:
    voyager:
        build: "./"
        container_name: voyager
        restart: unless-stopped
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./Logs/:/app/Logs/"
            - "./.env:/app/.env"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.voyager.entrypoints=web,websecure"
            - "traefik.http.routers.voyager.rule=Host(`voyager-api.alphiealph.me`)"
            - "traefik.http.routers.voyager.service=voyager"
            - "traefik.http.services.voyager.loadbalancer.server.port=8765"
            - "traefik.http.routers.voyager.tls=true"
        depends_on:
            - mongo
        networks:
            - traefik-net
            - voyager-net

    mongo:
        image: mongo:7-jammy
        restart: unless-stopped
        container_name: voyager-mongo
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/var/opt/lunarlabs/voyager/mongo-data:/data/db"
        env_file:
            - path: ./Mongo/.env
              required: true
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        networks:
            - voyager-net

    traefik:
        image: "traefik:latest"
        container_name: traefik
        restart: unless-stopped
        security_opt:
            - "no-new-privileges:true"
        networks:
            - traefik-net
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./Traefik/traefik.yml:/traefik.yml:ro"
            - "./Traefik/acme.json:/acme.json"
            - "./Traefik/configs:/configurations"
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-net
            - traefik.http.routers.traefik-secure.entrypoints=websecure
            - traefik.http.routers.traefik-secure.rule=Host(`traefik.alphiealph.me`)
            - traefik.http.routers.traefik-secure.service=api@internal
            - traefik.http.routers.traefik-secure.middlewares=user-auth@file

networks:
    traefik-net:
        name: "traefik-net"
    voyager-net:
        name: "voyager-net"