# Dynamic configuration
http:
  middlewares:
    traefik-https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    # sslheader:
    #   headers:
    #     sslRedirect: true
    #     forceSTSHeader: true
    #     stsIncludeSubdomains: true
    #     stsPreload: true
    #     stsSeconds: 31536000
    #     customrequestheaders:
    #       X-Forwarded-Proto: "https"
    user-auth:
      basicAuth:
        users:
          - "admin:$apr1$vrGy.yGR$ErMEKiDrV85ZrEwDu2kqZ0"
  routers:
    traefik:
      entrypoints:
        - http
      rule: Host(`traefik.lunarlabs.cc`)
      middlewares:
        - traefik-https-redirect@file
    traefik-secure:
      entrypoints:
        - https
      rule: Host(`traefik.lunarlabs.cc`)
      service: api@internal
      middlewares:
        - user-auth@file
      tls:
        certResolver: cloudflare
        domains:
          - main: lunarlabs.cc
            sans:
              - "*.lunarlabs.cc"

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12
