# Static configuration
api:
  dashboard: true
  debug: true

log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 1000

serversTransport:
  insecureSkipVerify: true
  
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /traefik.yml
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: 17bestradiol@proton.me
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

tls:
  options:
    default:
      sniStrict: true
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: ":443"
    http:
      middlewares:
        - security-headers@file
      tls:
        certResolver: cloudflare
        domains:
          - main: lunarlabs.cc
            sans:
              - "*.lunarlabs.cc"
        options: default



# Dynamic configuration
http:
  middlewares:
    security-headers:
      headers:
        referrerPolicy: no-referrer
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          X-Powered-By: "Redstone"
          Server: "Server"

    api-auth:
      basicAuth:
        users:
          - "admin:$apr1$vrGy.yGR$ErMEKiDrV85ZrEwDu2kqZ0"

  routers:
    traefik-secure:
      entrypoints:
        - web-secure
      rule: Host(`traefik.lunarlabs.cc`)
      service: api@internal
      middlewares:
        - api-auth