api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: ":443"
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: itzbunniyt@gmail.com
      storage: acme.json
      keyType: EC384
      dnschallenge:
        provider: cloudflare
        delayBeforeCheck: 300
        resolvers:
          - 8.8.8.8:53
      httpChallenge:
        entryPoint: web